Merge pull request #2 from OmarHamed0/login_feature_SCRUM-1
OmarHamed0/flower_app pull request #4
Opened 2024-11-18 21:05 UTC by OmarHamed0

add gust user

2024-11-18 22:23 UTC, ahmed-sala commented on lib/src/presentation/managers/sign_in/sign_in_actions.dart
>  class SignInClickAction extends SignInActions{}
name it SigninAction better

2024-11-18 22:25 UTC, ahmed-sala commented on lib/src/presentation/pages/sign_in/sign_in_screen_body.dart
> +          _goNextHome(context);
merge from development and then merge

2024-11-18 22:26 UTC, ahmed-sala requested changes
merge from dev

2024-11-19 18:31 UTC, ahmed-sala approved these changes

2024-11-19 18:39 UTC, ali72-20 approved these changes
all done

2024-11-19 19:33 UTC, merged